default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: deeplegal_development
test:
  <<: *default
  database: deeplegal_test
production:
  <<: *default
  database: deeplegal_production
  username: deeplegal
  password: <%= ENV['DEEPLEGAL_DATABASE_PASSWORD'] %>
