default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: laboral_development
  username: root
test:
  <<: *default
  database: laboral_test
production:
  <<: *default
  database: laboral
  username: root
