default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: laboral_development
  username: root
test:
  <<: *default
  database: laboral_test
production:
  <<: *default
  host: <%= Rails.application.secrets.laboral_db_host %>
  port: 3306
  database: laboral
  username: root
